-- Extensiones (opcional: si no usas UUID, puedes omitir pgcrypto)
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 1. Usuario
CREATE TABLE IF NOT EXISTS users (
    user_id        SERIAL PRIMARY KEY,
    first_name     VARCHAR(255),
    last_name      VARCHAR(255),
    email          VARCHAR(255) NOT NULL UNIQUE,
    password_hash  VARCHAR(255) NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);
/* Elimina redundancias:
   - Quité CONSTRAINT ux_users_first_name (suele ser indeseada).
   - Quité CONSTRAINT ux_users_email y el idx_users_email (ya hay UNIQUE). */

-- 3. Country
CREATE TABLE IF NOT EXISTS country (
  country_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR(100) NOT NULL UNIQUE,
  iso_code    CHAR(3) NOT NULL UNIQUE
);

-- 4. City
CREATE TABLE IF NOT EXISTS city (
  city_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  country_id  INTEGER NOT NULL REFERENCES country(country_id),
  name        VARCHAR(100) NOT NULL,
  CONSTRAINT ux_city_country_name UNIQUE (country_id, name)
);
CREATE INDEX IF NOT EXISTS idx_city_country ON city (country_id);

-- 5. Role
CREATE TABLE IF NOT EXISTS role (
  role_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR(50) NOT NULL UNIQUE,
  description VARCHAR(255)
);

-- 6. Privilege
CREATE TABLE IF NOT EXISTS privilege (
  privilege_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         VARCHAR(50) NOT NULL UNIQUE,
  description  VARCHAR(255)
);

-- 7. Role_Privilege (M:N)
CREATE TABLE IF NOT EXISTS role_privilege (
  role_id        INTEGER NOT NULL REFERENCES role(role_id) ON DELETE CASCADE,
  privilege_id   INTEGER NOT NULL REFERENCES privilege(privilege_id) ON DELETE CASCADE,
  assigned_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (role_id, privilege_id)
);
-- Índice para búsquedas por privilege_id
CREATE INDEX IF NOT EXISTS idx_role_privilege_priv ON role_privilege (privilege_id);

-- 8. User_Role (M:N)
CREATE TABLE IF NOT EXISTS user_role (
  user_id      INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  role_id      INTEGER NOT NULL REFERENCES role(role_id) ON DELETE CASCADE,
  assigned_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, role_id)
);
/* No creamos idx_user_role_u porque el PK (user_id, role_id) ya cubre user_id.
   Sí dejamos el índice por role_id para búsquedas inversas. */
CREATE INDEX IF NOT EXISTS idx_user_role_r ON user_role (role_id);

-- 9. Video_Status
CREATE TABLE IF NOT EXISTS video_status (
  status_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR(30) NOT NULL UNIQUE,
  description VARCHAR(255)
);

-- 2. Player (1:1 with User)
CREATE TABLE IF NOT EXISTS player (
  user_id       INTEGER PRIMARY KEY REFERENCES users(user_id) ON DELETE CASCADE,
  city_id       INTEGER NOT NULL REFERENCES city(city_id),
  registered_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_player_city ON player (city_id);

-- 10. Video
CREATE TABLE IF NOT EXISTS video (
  video_id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  player_id          INTEGER NOT NULL REFERENCES player(user_id) ON DELETE CASCADE,
  title              VARCHAR(255) NOT NULL,
  original_file      VARCHAR(255) NOT NULL,
  processed_file     VARCHAR(255),
  status_id          INTEGER NOT NULL REFERENCES video_status(status_id),
  uploaded_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  processed_at       TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_video_player ON video (player_id);
CREATE INDEX IF NOT EXISTS idx_video_status ON video (status_id);

-- 11. Vote
CREATE TABLE IF NOT EXISTS vote (
  vote_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  video_id   INTEGER NOT NULL REFERENCES video(video_id) ON DELETE CASCADE,
  voted_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT unique_vote_user_video UNIQUE (user_id, video_id)
);
CREATE INDEX IF NOT EXISTS idx_vote_user  ON vote (user_id);
CREATE INDEX IF NOT EXISTS idx_vote_video ON vote (video_id);
