name: Worker Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-workers:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        worker: [AudioRemoval, EditVideo, TrimVideo, Watermarking, gossipOpenClose]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.21'
    
    - name: Install dependencies
      working-directory: ./${{ matrix.worker }}
      run: |
        go mod download
        go install github.com/golang/mock/mockgen@latest
    
    - name: Generate mocks
      working-directory: ./${{ matrix.worker }}
      run: go generate ./...
    
    - name: Run tests
      working-directory: ./${{ matrix.worker }}
      run: go test -v ./tests/unit/...
    
    - name: Generate coverage
      working-directory: ./${{ matrix.worker }}
      run: |
        go test -coverprofile=coverage.out ./tests/unit/...
        go tool cover -func=coverage.out
    
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        file: ./${{ matrix.worker }}/coverage.out
        flags: ${{ matrix.worker }}